### ISSUE TITLE
Balance component update GIF and description update

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/ss2-docs#20]
## Issue Overview

[The Balance Page](https://docs.scaffoldstark.com/components/Balance) is outdated. The current balance shows both ETH and STRK balances. Need update on this page and its descriptions

## Proposed Solutions or Ideas

- Your documentation should be clear and concise.
- Use images where appropriate
- Use proper styling and hierarchy for text
- Use proper styling for code and variable names.
- Use proper callouts when required

Refer to docusaurus for more info: https://docusaurus.io/

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am frontend developer and also skilled in technical documetation.i have a good understanding with technologies like Html, css, javascript, typescript , cario  . i have also successfully contributed to open source projects like arkproject, stark Quest, shinigami.

### How I plan on tackling this issue
I will approach the problem by 
Updating the balance page by separating ETH and STRK balances, use clear headings and concise descriptions, then  add visuals like icons or charts, style code properly, and use Docusaurus callouts for key info.

**Comment by devcollinss** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack blockchain developer developer.

### How I plan on tackling this issue
I will update the documentation for the Balance Page to reflect the current balances of both ETH and STRK accurately. The revised documentation will include a clear and concise description of the Balance Page, detailing how the balances are displayed and any relevant features or functionalities.

I will incorporate images to visually represent the updated Balance Page, helping users understand the layout and changes. The documentation will be structured with proper styling and hierarchy for text to enhance readability and ease of navigation.

For any code snippets or variable names, I will apply appropriate styling to ensure they stand out from regular text. Additionally, I will use callouts to emphasize key information, tips, or best practices regarding the Balance Page.

To ensure a polished presentation, I will refer to Docusaurus for guidance on documentation layout and design elements. After making the updates, I will review the documentation for accuracy and clarity before finalizing it.

**Comment by Nadai2010** [comment]
Hello, since @ShantelPeters already has an open issue, we will assign it to @devcollinss in order of preference.

**Comment by metalboyrick** [comment]
Hi @devcollinss , sorry for rushing in but we would like to remind you that ODHack8 is almost finished :( would encourage to start working on this issue and put out a PR ASAP, thanks in advance!
