### ISSUE TITLE
Add recipe for Read Contracts

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/ss2-docs#22]
## Issue Overview

Add a recipe tutorial on reading a contract from the network.

## Proposed Solutions or Ideas

- Your documentation should be clear and concise.
- Use images where appropriate
- Use proper styling and hierarchy for text
- Use proper styling for code and variable names.
- Use proper callouts when required

Refer to docusaurus for more info: https://docusaurus.io/

**Comment by od-hunter** [comment]
Hi @metalboyrick , please can I help you with this please? Pleaseeeee

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Please can I be assigned this issue? I am a blockchain Developer and I’m also good with documentations

### How I plan on tackling this issue
Below are some of the documentations I've done that were merged:

https://github.com/dojoengine/book/pull/308#event-13866062226

https://github.com/keep-starknet-strange/joyboy/pull/143#event-13034455918,

https://github.com/horuslabsio/Starknet-Scaffold/pull/94#event-13007360671.

https://github.com/Hyle-org/examples/pull/15

https://github.com/Hyle-org/examples/pull/16

https://github.com/horuslabsio/tokenbound-contract-docs/pull/11

Please I’m ready to work, assign me please.

**Comment by estherbreath** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am a smart contract developer and a technical writer.
I attended and came out with a gold medal from the prestigious Ethereum Writers Cohort 2023.
Leveraging on my knowledge, I have published articles and participated in hackathons as a developer and a technical writer.
I will leverage on my experiences to get this issue done well, and in a good time.

### How I plan on tackling this issue
Here's how I intend to go about the issue

    • Create a clear and concise tutorial on reading contracts from the network using Docusaurus.
    • Organize content with proper headings and styling. 
    • Include relevant images and code snippets formatted correctly. 
    • Use callouts for important notes or warnings. 
    • Implement versioning and translation features to ensure documentation stays up-to-date and accessible globally.

**Comment by Nadai2010** [comment]
All your @od-hunter

**Comment by metalboyrick** [comment]
Hi @od-hunter  , sorry for rushing in but we would like to remind you that ODHack8 is almost finished :( would encourage to start working on this issue and put out a PR ASAP, thanks in advance!

**Comment by od-hunter** [comment]
> Hi @od-hunter , sorry for rushing in but we would like to remind you that ODHack8 is almost finished :( would encourage to start working on this issue and put out a PR ASAP, thanks in advance!

Hello ser, will push a pr today
