### ISSUE TITLE
Add documentation for Local and Sepolia Faucets

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/ss2-docs#24]
## Issue Overview

We have added a faucet feature to address gas issues that developers might encounter. Currently we do not have any documentation on this feature yet.

## Proposed Solutions or Ideas

- Your documentation should be clear and concise.
- Use images where appropriate
- Use proper styling and hierarchy for text
- Use proper styling for code and variable names.
- Use proper callouts when required

Refer to docusaurus for more info: https://docusaurus.io/

**Comment by pheobeayo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am a Web3 front-end developer skilled in technical documentation and software development. I greatly understand technologies like JavaScript, Typescript, Cairo, Rust and Solidity. I have contributed successfully to open-source projects like Stark Quest

### How I plan on tackling this issue
My Approach includes Pull Request (PR) includes:
- Reviewing of existing Documentation:
By thoroughly reading the current documentation, including README files, code comments, and any other relevant information.
- Note changes and define all code snippets and technical terms simply.
-Make proper documentation on available local and Sepolia faucets.
- Create a Pull Request (PR)
- Request for a Review
- Make changes based on the Review of the PR

**Comment by devcollinss** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack blockchain developer developer and a technical writer

### How I plan on tackling this issue
I will create clear and concise documentation for the newly added faucet feature designed to address gas issues that developers may encounter. The documentation will include an overview of the faucet's purpose, how it works, and step-by-step instructions on how developers can utilize this feature effectively.

I will incorporate images where appropriate to illustrate the faucet feature in action, making it easier for users to understand its functionality. The documentation will follow a structured format, using proper styling and hierarchy for text to enhance readability and navigation.

For any code snippets or variable names, I will apply appropriate styling to distinguish them from regular text. I will also use callouts to highlight important information, best practices, or tips related to the faucet feature.

To ensure the documentation is user-friendly and professional, I will refer to Docusaurus for guidance on layout and design elements. After completing the documentation, I will review it for accuracy and clarity before finalizing it.

**Comment by Nadai2010** [comment]
All your @pheobeayo

**Comment by pheobeayo** [comment]
Thank you @Nadai2010 , I will get right on it

**Comment by metalboyrick** [comment]
Hi @pheobeayo  , sorry for rushing in but we would like to remind you that ODHack8 is almost finished :( would encourage to start working on this issue and put out a PR ASAP, thanks in advance!

**Comment by pheobeayo** [comment]
Okay, I am on it
