### ISSUE TITLE
[DOCS] Add docs recipe for  "Developing on a fork“

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/ss2-docs#60]
## Issue Overview

Outline instructions on how users can develop on a fork

## Proposed Solutions or Ideas

- Please clone the repo https://github.com/Scaffold-Stark/scaffold-stark-2 and get familiar with the features first before attempting. 
- We should be able to 

1. run yarn chain and spin up a localhost devnet fork from mainnet
2. deploy our contracts to mainnet
3. modify scaffold config to use fork network ( note the chain ID difference from devnet )
4. yarn your front end and execute transactions using burner wallets
5. should be able to connect your argent / braavos wallets to localhost / devnet network and execute transactions as well

**Comment by CollinsC1O** [comment]
Can I take this from here?

**Comment by vestor-dev** [comment]
i'm a frontend dev and blockchain dev 
May I try my hand at this?
i would love to work on this and get it done

**Comment by jedstroke** [comment]
Can I start working on this?

**Comment by abdegenius** [comment]
Can I jump on this task?

**Comment by 1nonlypiece** [comment]
Hi ,
I’d like to work on this issue as I have experience in creating and maintaining clear and user-friendly documentation..

ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by greatest0falltime** [comment]
Hi,

I’d be thrilled to work on this issue as I have a strong background in crafting well-structured and accessible documentation.

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  

Looking forward to contributing!

**Comment by 3th-Enjay** [comment]
Can I attempt this issue?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by emmz3230** [comment]
Is this issue still available?

I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute
to open-source documentation and help build documentation sites.

**Comment by kayceeDev** [comment]
I’d like to resolve this.

**Comment by sandragcarrillo** [comment]
I would like to get assing to this issue. I have completed Speedrun Stark challenge in the past and have a good idea on how to work with the repository and I like to make technical content so this would be a great opportunity to match the experience and help to this project. 

This is how I would work on this issue:

1. Clone the repository to get familiar with the features
2. Write a step-by-step guide covering: 
- Detailed steps to run a fork
- Interacting with the Fork
- Common workflows like creating branches, making changes, and submitting pull requests.
3. Submit PR with changes

**Comment by ShantelPeters** [comment]
Could I try solving this?

**Comment by Ekene001** [comment]
Hello I'm Ekene, a frontend and blockchain developer with proficiency in Rust, Typescript, react/next js and typescript, and I’m excited about the opportunity to collaborate and bring my skills to the table. 

please can i handle this task

**Comment by mimisavage** [comment]
I'd love to give this a go.

**Comment by TheSQLguy** [comment]
To address this issue, I would

Clone the repository from Scaffold-Stark GitHub and explore its features to understand the workflow.
Draft a process on forking the repository, making changes, and submitting contributions (e.g., forking, cloning, branching, making changes, and submitting a PR).
Include best practices for development and testing on a fork referencing the main repository to standardize.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by od-hunter** [comment]
Hi, can I be assigned this please? I am a blockchain developer and I'm also good at documentations. Below are some of the documentations I've done that were merged:

https://github.com/dojoengine/book/pull/308,
https://github.com/keep-starknet-strange/joyboy/pull/143,
https://github.com/Scaffold-Stark/ss2-docs/pull/31,
https://github.com/horuslabsio/Starknet-Scaffold/pull/94,
https://github.com/Hyle-org/examples/pull/15,

Please I’m ready to work, assign me please.

**Comment by Luluameh** [comment]
Is it okay if I tackle this?

**Comment by suhas-sensei** [comment]
I’d love to work on this task. i have experience in rust, cairo and ts, having worked in previous od hacks, but never worked on docs because most of them were easy, seeing the hard label makes me want to take up the challenge. Hoping to tap in this new realm.

**Comment by ikezuby2012** [comment]
I’d like to work on this.

**Comment by emarc99** [comment]
Can I tackle this one? I have done similar documentation issue on ODhack. And I like doing research: https://emarc.hashnode.dev/starknet-development-with-docker-a-streamlined-setup-for-cairo-builders

**Comment by olisaagbafor** [comment]
Can I take care of this issue?

**Comment by metalboyrick** [comment]
all yours @suhas-sensei

**Comment by suhas-sensei** [comment]
thanks for the assignment.

**Comment by metalboyrick** [comment]
hey @suhas-sensei , any updates here?

**Comment by suhas-sensei** [comment]
yeah, I'm sending a pr today
