### ISSUE TITLE
[DOCS] Add a search engine, magnifying glass or similar

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/ss2-docs#61]
## Issue Overview

We need something to search the documentation with. 

## Proposed Solutions or Ideas

Docusaurus Search: https://docusaurus.io/docs/search

**Comment by Supa-mega** [comment]
Could I try solving this?

**Comment by 1nonlypiece** [comment]
Hi ,
I’d like to work on this issue as I have experience in creating and maintaining clear and user-friendly documentation..

ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by aniruddhaaps** [comment]
To fix this problem, I would:

Add Docusaurus Search to documentation using the Docusaurus search guide.
Index all relevant pages of the documentation in search for comprehensive results by configuring search.
Test the functionality to ensure correct and friendly searches with room to make better optimizations.

**Comment by caxtonacollins** [comment]
I will love to start working on this. Please assign me.

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience in developing comprehensive and user-focused documentation. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi,

I’d be thrilled to work on this issue as I have a strong background in crafting well-structured and accessible documentation.

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  

Looking forward to contributing!

**Comment by chigozzdevv** [comment]
Could I take a shot at this?

**Comment by emmz3230** [comment]
Can I try solving this issue?

I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute
to open-source documentation and help build documentation sites.

**Comment by kayceeDev** [comment]
I’m interested in this one.

**Comment by mimiprosper** [comment]
I would like to take this task. Am a web 2 frontend developer, a technical writer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. 
If assigned this i would complete it within 2 days. 

Here are some articles i have written: https://medium.com/@emma.onyedika.okeke

**Comment by ShantelPeters** [comment]
Would love to tackle this!

**Comment by mimisavage** [comment]
Can I take this issue?

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by TheSQLguy** [comment]
To fix this problem, I would:

Add Docusaurus Search to documentation using the Docusaurus search guide.
Index all relevant pages of the documentation in search for comprehensive results by configuring search.
Test the functionality to ensure correct and friendly searches with room to make better optimizations.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by metalboyrick** [comment]
hey @mimisavage, any updates here?
