### ISSUE TITLE
[DOCS] Add tutorial on installing `starknet-devnet` with `asdf`

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/ss2-docs#62]
## Issue Overview

Update the docs with tutorial on how to install `starknet-devnet` with `asdf`.

## Proposed Solutions or Ideas

Tutorial from docs: https://0xspaceshard.github.io/starknet-devnet-rs/docs/running/install#install-with-asdf

**Comment by OWK50GA** [comment]
Is it okay if I take this?
I'm Wilfrid Okorie, and I'll like to take this opportunity to contribute to this project

**Comment by SimplementeCao** [comment]
---

### Hey! I'm *SimplementeCao*. 👋

I have contributed before to other projects like:

- `Cairo Book`
- `Starknet Book`
- `Starknet Docs`
- `Starknet Security Challenges Factory`
- `Starkane`

Can I work on this issue?

Check my OnlyDust, I've contributed to many projects: [OnlyDust Profile](https://app.onlydust.com/u/SimplementeCao), 
and my [GitHub](https://github.com/SimplementeCao)

---

### Plan to Solve the Issue:

1. **Analyze the codebase** to understand the current structure and functionality.
2. **Review the problem description** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I face any challenge, I will **ask questions promptly** in the relevant support group or communication channel to move forward efficiently.
5. Once resolved, I will **open a PR** and wait for your feedback.

---

Let me know if I can start working on this! 🚀

---

**Comment by jedstroke** [comment]
May I take care of this?

**Comment by CollinsC1O** [comment]
Hello @metalboyrick I'm a front-end and a blockchain developer, I write cairo and I will love to work on this. Please assign

**Comment by GideonBature** [comment]
Can I try solving this issue?

Could I be assigned to this?

My name is Gideon Bature, a Software Engineer, I have experience working with Cairo as well as have contributed to the Cairo book/documentation, I also write technical articles and documentations . If given the opportunity, I will send my first PR within 48 hours.

Thank you!

**Comment by vestor-dev** [comment]
Can I take care of this issue?

**Comment by abdegenius** [comment]
I’d like to resolve this.

**Comment by 1nonlypiece** [comment]
Hi ,
I’d like to work on this issue as I have experience in creating and maintaining clear and user-friendly documentation..

ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by aniruddhaaps** [comment]
To address this issue, I would

Refer to the starknet-devnet installation tutorial.
Add a step-by-step guide in the documentation on installing starknet-devnet using asdf, making it easy for developers to understand and implement.
Test the instructions by exercising them on a clean setup and include any troubleshooting tips if necessary.

**Comment by chigozzdevv** [comment]
I'd like to handle this task.

**Comment by 3th-Enjay** [comment]
May I take this issue on?

**Comment by emmz3230** [comment]
I'd love to give this a go.

I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute
to open-source documentation and help build documentation sites.

**Comment by 7-falseparfait** [comment]
Mind if I try this one?

This is my first time contributing here, and I would love to have the opportunity to contribute to this documentation. While I specialize in JavaScript, I’m excited to help with updating the docs and providing a tutorial on how to install starknet-devnet using asdf. Looking forward to contributing and learning more!

**Comment by mimiprosper** [comment]
I would like to take this task. Am a web 2 frontend developer, a technical writer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. 
If assigned this i would complete it within 2 days. 

Here are some articles i have written: https://medium.com/@emma.onyedika.okeke

**Comment by ShantelPeters** [comment]
I'd like to handle this task.
